language: node_js
node_js:
  - "7"
  
cache:
  bundler: true
  directories:
    - node_modules

  script: 
    - npm run report

  after success: 
    - cat ./coverage/**/lcov.info | ./node_modules/coveralls/bin/coveralls.js