language: node_js
node_js:
  - "7"
  
cache:
  bundler: true
  directories:
    - node_modules

env:
  - TRAVIS=true

script:
  - npm test
  - npm run servertest

after_success: 
  - npm run coveralls